# Use a lightweight Nginx image
FROM nginx:alpine

# Copy the static files from the frontend directory to the Nginx html directory
COPY . /usr/share/nginx/html

# Expose port 80 for the web server
EXPOSE 80
